
DROP TABLE IF EXISTS `City_tbl`;
CREATE TABLE IF NOT EXISTS `City_tbl` (
  `CityId` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(5000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `InsertedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CityId`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=16503 ;
